version: '3'

services:
  magento-mam:
    container_name: magento-web-mam
    build:
      context: web-base
    image: magento-web-mam
    volumes:
      - ./src:/var/www/html/
    environment:
      - SERVER_NAME=gs.tech.test
      - MAGE_IS_DEVELOPER_MODE=true # myst be false in prod
      - AWS_ACCESS_KEY_ID=AKIAXSVYJD7WDUCYJ6WZ #should not be in git for security reasons
      - AWS_SECRET_ACCESS_KEY=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 #should not be in git for security reasons
      - NEW_ORDER_STANDARD=https://sqs.ap-south-1.amazonaws.com/521151258604/new-order-standard
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - web
      - internal
  mysql-mam:
    container_name: magento-db-mam
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=magento
      - MYSQL_USER=magento
      - MYSQL_PASSWORD=password
    volumes:
        - ./storage/dumps:/docker-entrypoint-initdb.d
        - ./storage/db:/var/lib/mysql:rw
    networks:
        - internal
networks:
  web:
    external:
      name: web
  internal:
    driver: bridge